export const GENRES_LIST = [
  'Adventure',
  'Biography',
  'Children\'s',
  'Contemporary',
  'Crime',
  'Detective',
  'Drama',
  'Dystopian',
  'Essays',
  'Fantasy',
  'Fiction',
  'Flash Fiction',
  'Historical',
  'Historical Fiction',
  'Horror',
  'Indie/Experimental',
  'LGBTQ+',
  'Legal Thriller',
  'Literary Fiction',
  'Memoir',
  'Mystery',
  'New Adult (NA)',
  'Non-Fiction',
  'Novellas',
  'Paranormal',
  'Picture Books',
  'Poetry',
  'Psychological Thriller',
  'Romance',
  'Sci-Fi',
  'Science Fiction',
  'Self-Help',
  'Short Stories',
  'Supernatural',
  'Thriller',
  'Young Adult (YA)',
]
